### PR TITLE
🚩: Milestone 2: bookstore | feature/addReducersAndActions

### PR DESCRIPTION
**Pull request by Ruthmy**
### Here is a summary of what has been done:

- I added the React-Redux library and the Redux Toolkit.
- Create the directory `/src/redux` to contain all the Redux logic.
- Configure a Redux store.
- Create the `booksSlice` and `categoriesSlice` slices.
    - Create the `addBook` and `removeBook` reducers.
    - Create the `checkStatus` reducer.
- Structure the app files using a 'feature folder' aproach.

### In this new Branch, I have **ADDED** the succeeding **\*📂 folders** and **\*\*📄 files**.

- ### 📂\* src/redux/

     - \*\*📄 store.js

          > I have added the `store.js`. This file holds the whole state tree of the application.

   - ### 📂\* books/

     - \*\*📄 booksSlice.js

          > I have added the `booksSlice.js`. This file contains the `books` slice of the state tree.
          > It contains the empty `books` array for the initial state and the `addBook` and `removeBook` reducers.

   - ### 📂\* categories/

     - \*\*📄 categoriesSlice.js

          > I have added the `categoriesSlice.js`. This file contains the `categories` slice of the state tree.
          > It contains the empty `categories` array for the initial state and the `checkStatus` reducer.

### In this Branch, I have **MODIFIED** the succeeding **📂\* folders** and **📄\*\* files**

- ### 📂\* root/
    - \*\*📄 package.json
    - \*\*📄 package-lock.json

         > I added the `react-redux` and `@reduxjs/toolkit` libraries.

   - ### 📂\* src/components/

     - \*\*📄 AddForm.js

         > I added `useDispatch` hook to dispatch the `addBook` action creator.

     - \*\*📄 Item.js

         > I added `useDispatch` hook to dispatch the `deleteBook` action creator.

     - \*\*📄 index.js

         > I added `Provider` component to wrap the `App` component.
         > I added the Redux store to the `Provider` component.

---

### Thank you for taking the time to review this PR ⭐!

---

### CODE REVIEW

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Required Changes 🔁
## Hello @Ruthmy   👋 🙂

You're doing a great job on your project. We're proud of you. Good job so far! 

It's OK to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job. 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Flow
  ✅  Descriptive Pull Request
  ✅  No linter errors

## Required Changes ♻️

- [ ] Dear @Ruthmy, you're using old information for the project in the README file. Currently, it displays information related to Math Magicians but as you know currently you're working on Bookstore project. Kindly update your README file 👍 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ruthmy** [comment]
Hi @zainsadaqat !
You're totally right, I forgot to change that, I will fix it.
Thank you very much for your feedback ✨

**Review by ShadyShawkat — APPROVED** [review]
## Hi @Ruthmy, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 
- Your readme looks professional ✔️ 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ruthmy** [comment]
Thank you very much @ShadyShawkat =DD

**Pull request merged**
