### PR TITLE
🚩: Milestone 1: bookstore | feature/basicSetUpAndComponents - >>branch<< -

### PR DESCRIPTION
**Pull request by Ruthmy**
### Here is a summary of what has been done:

- Create a React application is using [Create React App](https://create-react-app.dev/)
- Follow [Gitflow Workflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) in this repository.
- Set the linters for [React & Redux](https://github.com/microverseinc/linters-config/tree/master/react-redux)
- Installed React Router V6.
- Added 2 routes in the app: `/` and `/categories`.
- Added the following components to the `src/components/` folder.
    - Main component | `App.js`
    - For the individual book state | `Item.js`
    - To list the individual books | `DisplayBooks.js`
    - A form to create new books | `AddForm.js`
    - For the navigation and links created | `Navbar.js`
    - For the category section | `Categories.js`

### In this new Branch, I have **ADDED** the succeeding **\*📂 folders** and **\*\*📄 files**. to complete this [Milestone's requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/project_init_project_wth_comps_v3_0.md)

- ### 📂\* root/

     - \*\*📄 .babelrc
     - \*\*📄 .eslintrc.json
     - \*\*📄 .gitignore
     - \*\*📄 .stylelintrc.json
     - \*\*📄 LICENSE
     - \*\*📄 package-lock.json
     - \*\*📄 package.json
     - \*\*📄 README.md

   - ### 📂\* .github/workflows/
     - \*\*📄 linters.yml

   - ### 📂\* public/
     - \*\*📄 favicon.ico
     - \*\*📄 index.html
     - \*\*📄 logo192.png
     - \*\*📄 logo512.png
     - \*\*📄 manifest.json
     - \*\*📄 robots.txt

   - ### 📂\* src/

     - \*\*📄 index.js

          > I have added the `index.js` file to the `src/` folder. This file is the entry point of the React App.

     - \*\*📄 index.css
     - \*\*📄 setupTests.js

   - ### 📂\* src/bd/

     - \*\*📄 BooksList.js

          > I have added the `BooksList.js` file to the `src/bd/` folder. This file contains the array of books.

     - \*\*📄 MenuData.js

          > I have added the `MenuData.js` file to the `src/bd/` folder. This file contains the array of routes.

   - ### 📂\* src/components/

     - \*\*📄 AddForm.js

          > Component for the Add Book Form.

     - \*\*📄 Categories.js

          > Component for the `Categories` section.
          > It contains a basic text to warn that it is under construction.

     - \*\*📄 DisplayBooks.js

          > Component for the `Book` section. It contains the `AddForm` and the `Item` components.
          > This component create a list of `Item` components from the `BooksList` array.

     - \*\*📄 Item.js

          > Component for the `Book` item. It contains the `Book` title, author and category.
          > It also contains the `Remove` button.

     - \*\*📄 Navbar.js

          > Component for the `Navbar` section in the `App` component.
          > This component create a list of `Link` components from the `MenuData` array.

   - ### 📂\* src/styles/

     - \*\*📄 AddForm.css
     - \*\*📄 App.css
     - \*\*📄 Categories.css
     - \*\*📄 DisplayBooks.css
     - \*\*📄 Item.css
     - \*\*📄 Navbar.css

          > I have added the all this `.css` file to the `src/styles/` folder. This files contain the most basic styles for each one of the components.

### In this Branch, I have **MODIFIED** the succeeding **📂\* folders** and **📄\*\* files**

- ### 📂\* root/
    - \*\*📄 README.md

         > I have documented the project following Microverse Guidelines.

   - ### 📂\* src/components/

     - \*\*📄 App.js

          > Main component for the Bookstore Project. It contains the `Navbar` and the `DisplayBooks` components.
          > It also contains the Routes for the `DisplayBooks` and the `Categories` components.
          > I have added the `HashRouter` component to wrap the `App` component routes.
          > I have added new imports for the react-router-dom and the other components.

---

### Thank you for taking the time to review this PR ⭐!

---

### CODE REVIEW

**Comment by Ruthmy** [comment]
Dear Code Reviewer, 
This project contains some styles, although they are not mandatory for the activity, some were necessary, for example, to put the elements in a single line, others were transferred from reused components (such as the Navbar used in Math Magician).
Thank you very much for your time in this review.

**Review by fobadara — CHANGES_REQUESTED** [review]
Hi @Ruthmy, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Good first attempt
✅ Descriptive README

## Required Changes ♻️
_Check the comments under the review._
I had to include some comments here because the affected file could not be accessed for inline comments
[REQUIRED] Kindly change the name of your app file from `Bookstore` back to `app`. It is better to follow conventions in this case. It took me a while to find the file just because you changed the name.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ruthmy** [comment]
Hi @fobadara ! Thank you very much for your feedback.
I have completed the changes you requested.
Thanks for your time.

**Review by tufoinnkuo10 — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @Ruthmy 

Your project is complete! Great job  🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- components well added
- No linter errors



--- [optional] Please ensure your PR summary always carry the key points of what you did in that milestone and not all parts and section of your project. nice work.
<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ruthmy** [comment]
Hi @tufoinnkuo10 !
Thank you very much for your review and your advice. I will work on applying it in the future.
Happy weekend.

**Pull request merged**
